version: "3.9"


services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn dockerized_django.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/static
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  redis:
    image: redis:alpine

  celery:
    build: ./app
    command: celery -A dockerized_django worker -l info
    volumes:
      - ./app/:/usr/src/app/
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
      - web

  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static_volume:/home/app/web/static
    depends_on:
      - web


volumes:
  postgres_data:
  static_volume:
