version: "3.9"


services:
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - '8000:8000'
    env_file:
      - ./.env.dev
  db:
    image: postgres:13.0-alpine
    # connect to localhost:<port>
    ports:
      - "5432:5432"
    #
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  redis:
    image: redis:alpine
    # connect to localhost:<port>
    ports:
      - "6379:6379"
    #
  celery:
    build: ./app
    command: celery -A dockerized_django worker -l info
    volumes:
      - ./app/:/usr/src/app/
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
      - web

volumes:
  postgres_data:
